COMP = g++
FLAG = -o
INPT = BluePentagon.cpp
FBCK = -lGL -lGLEW -lglfw
OUTP = app

all : program1

program1 : 
	@echo "Compile your program"
	${COMP} ${FLAG} ${OUTP} ${INPT} ${FBCK}
	@echo "Your program are ready"

clean :
	@echo "Cleaning up ..."
	rm ${OUTP}
